-- Temporarily disable RLS for development
ALTER TABLE roasters DISABLE ROW LEVEL SECURITY;
ALTER TABLE coffees DISABLE ROW LEVEL SECURITY;
ALTER TABLE bags DISABLE ROW LEVEL SECURITY;
ALTER TABLE brews DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_preferences DISABLE ROW LEVEL SECURITY;